//! RPC server: a line-delimited JSON inference endpoint over TCP.
//!
//! Request  (one JSON object per line):
//!   {"prompt": "hello", "max_tokens": 32, "temp": 0.0, "seed": 42}
//! Response (one JSON object per line):
//!   {"ok": true, "generated": N, "text": "...", "tokens": [...],
//!    "tok_per_s": X, "hit_rate": Y}
//!
//! The engine holds mutable per-request state (KV cache, scratch), so requests
//! are served strictly one at a time on this thread — simple and correct for a
//! v0 node. Continuous batching is a later concern.

const std = @import("std");
const Io = std.Io;
const net = std.Io.net;
const engine_mod = @import("engine.zig");
const Engine = engine_mod.Engine;
const tokenizer = @import("tokenizer.zig");
const stats = @import("stats.zig");

pub const Ctx = struct {
    gpa: std.mem.Allocator,
    io: Io,
    engine: *Engine,
    addr: []const u8,
    port: u16,
    seed: u64,
    /// The engine holds mutable per-request state, so generation is serialized
    /// across connections by this mutex; connections otherwise run concurrently
    /// so one idle/slow client never blocks the accept loop.
    engine_lock: Io.Mutex = .init,
};

const Conn = struct { ctx: *Ctx, stream: net.Stream };

pub fn serve(ctx: *Ctx) !void {
    var address = try net.IpAddress.parse(ctx.addr, ctx.port);
    var server = try address.listen(ctx.io, .{ .reuse_address = true });
    defer server.deinit(ctx.io);

    while (true) {
        const stream = server.accept(ctx.io) catch continue;
        const conn = ctx.gpa.create(Conn) catch {
            stream.close(ctx.io);
            continue;
        };
        conn.* = .{ .ctx = ctx, .stream = stream };
        const t = std.Thread.spawn(.{}, connThread, .{conn}) catch {
            stream.close(ctx.io);
            ctx.gpa.destroy(conn);
            continue;
        };
        t.detach();
    }
}

fn connThread(conn: *Conn) void {
    handleConn(conn.ctx, conn.stream) catch {};
    conn.ctx.gpa.destroy(conn);
}

fn handleConn(ctx: *Ctx, stream: net.Stream) !void {
    defer stream.close(ctx.io);
    var rbuf: [1 << 16]u8 = undefined;
    var wbuf: [1 << 16]u8 = undefined;
    var r = stream.reader(ctx.io, &rbuf);
    var w = stream.writer(ctx.io, &wbuf);
    const ri = &r.interface;
    const wi = &w.interface;

    while (true) {
        const raw = ri.takeDelimiterInclusive('\n') catch return;
        const line = std.mem.trimEnd(u8, raw, "\r\n");
        if (line.len == 0) continue;
        handleRequest(ctx, line, wi) catch |e| {
            try wi.print("{{\"ok\":false,\"error\":\"{s}\"}}\n", .{@errorName(e)});
            try wi.flush();
        };
    }
}

fn handleRequest(ctx: *Ctx, line: []const u8, wi: *Io.Writer) !void {
    const gpa = ctx.gpa;
    var parsed = std.json.parseFromSlice(std.json.Value, gpa, line, .{}) catch {
        try wi.print("{{\"ok\":false,\"error\":\"invalid_json\"}}\n", .{});
        try wi.flush();
        return;
    };
    defer parsed.deinit();

    if (parsed.value != .object) {
        try wi.print("{{\"ok\":false,\"error\":\"expected_object\"}}\n", .{});
        try wi.flush();
        return;
    }
    const obj = parsed.value.object;

    const prompt_str = switch (obj.get("prompt") orelse .null) {
        .string => |s| s,
        else => {
            try wi.print("{{\"ok\":false,\"error\":\"missing_prompt\"}}\n", .{});
            try wi.flush();
            return;
        },
    };
    const max_tokens: usize = jsonUint(obj.get("max_tokens"), 32);
    const temp: f32 = @floatCast(jsonFloat(obj.get("temp"), 0.0));
    const seed: u64 = jsonUint64(obj.get("seed"), ctx.seed);

    const prompt = try tokenizer.encode(gpa, prompt_str);
    defer gpa.free(prompt);

    var produced = std.ArrayList(usize).empty;
    defer produced.deinit(gpa);

    ctx.engine_lock.lockUncancelable(ctx.io);
    const t0 = stats.nowNs(ctx.io);
    const n = ctx.engine.generate(prompt, max_tokens, temp, seed, &produced) catch |e| {
        ctx.engine_lock.unlock(ctx.io);
        return e;
    };
    const t1 = stats.nowNs(ctx.io);
    const hit_rate = ctx.engine.cache.stats.hitRate();
    ctx.engine_lock.unlock(ctx.io);
    const secs = @as(f64, @floatFromInt(t1 - t0)) / 1e9;
    const tok_s = if (secs > 0) @as(f64, @floatFromInt(n)) / secs else 0;

    // build response
    try wi.print("{{\"ok\":true,\"generated\":{d},\"text\":", .{n});
    try writeJsonString(wi, produced.items);
    try wi.print(",\"tokens\":[", .{});
    for (produced.items, 0..) |tok, i| {
        if (i != 0) try wi.print(",", .{});
        try wi.print("{d}", .{tok});
    }
    try wi.print("],\"tok_per_s\":{d:.2},\"hit_rate\":{d:.4}}}\n", .{ tok_s, hit_rate });
    try wi.flush();
}

/// Emit the generated bytes as a JSON string with proper escaping.
fn writeJsonString(wi: *Io.Writer, tokens: []const usize) !void {
    try wi.print("\"", .{});
    for (tokens) |tok| {
        const b = tokenizer.decodeByte(tok);
        switch (b) {
            '"' => try wi.print("\\\"", .{}),
            '\\' => try wi.print("\\\\", .{}),
            '\n' => try wi.print("\\n", .{}),
            '\r' => try wi.print("\\r", .{}),
            '\t' => try wi.print("\\t", .{}),
            0x20...0x21, 0x23...0x5b, 0x5d...0x7e => try wi.print("{c}", .{b}),
            else => try wi.print("\\u{x:0>4}", .{b}),
        }
    }
    try wi.print("\"", .{});
}

fn jsonUint(v: ?std.json.Value, default: usize) usize {
    return switch (v orelse .null) {
        .integer => |i| if (i < 0) default else @intCast(i),
        else => default,
    };
}
fn jsonUint64(v: ?std.json.Value, default: u64) u64 {
    return switch (v orelse .null) {
        .integer => |i| if (i < 0) default else @intCast(i),
        else => default,
    };
}
fn jsonFloat(v: ?std.json.Value, default: f64) f64 {
    return switch (v orelse .null) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        else => default,
    };
}
